### ISSUE TITLE
When using SA creator script, it errors out

### ISSUE THREAD

**Issue by cewong2** [CyberPoison/AutoRcloneV2#3]
After going through the authentication screen I get presented with this:

Traceback (most recent call last):
  File "/Users/cewong2/Downloads/AutoRcloneV2/gen_sa_accounts.py", line 311, in <module>
    resp = serviceaccountfactory(
  File "/Users/cewong2/Downloads/AutoRcloneV2/gen_sa_accounts.py", line 175, in serviceaccountfactory
    with open(token, 'wb') as t:
PermissionError: [Errno 13] Permission denied: 'token.pickle'

using Mac OS 12.6.7

**Comment by cewong2** [comment]
Figured it out, when using the procedures from the readme, it's

1: still the original directions, so the directory it creates is AutoRcloneV2 not AutoRclone, and since it creates it in user directory, it is only given read access, so even if you move it to a read/write folder you still need to change and give it read/write privileges for everyone.
